---
controller_credentials:
- name: Github
  description: Credentials for GitHub
  organization: "{{ awx_organization }}"
  credential_type: Source Control
  state: present
  inputs:
    username: "{{ github_user }}"
    password: "{{ github_password }}" 
- name: WindowsAdmin
  description: Machine Credential for AD domain
  organization: "{{ awx_organization }}"
  credential_type: Machine
  state: present
  inputs:
    username: "{{ windows_user }}"
    password: "{{ windows_password }}"
- name: VMWare vCenter
  description: Machine Credential example with become_method input
  organization: "{{ awx_organization }}"
  credential_type: VMware vCenter
  state: present
  inputs:
    host: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
- name: satellite
  description: Satellite 6 inventory plugin creds
  organization: "{{ awx_organization }}"
  credential_type: Red Hat Satellite 6
  state: present
  inputs:
    username: "{{ satellite_user }}"
    password: "{{ satellite_password }}"
    host: "https://{{ satellite_host }}"
- name: LinuxSSH
  description: Machine Credential for linux machines
  organization: "{{ awx_organization }}"
  credential_type: Machine
  state: present
  inputs:
    username: "{{ linux_user }}"
    ssh_key_data: "{{ linux_ssh_key }}"